trigger:
- main

pool: default

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(59abaf63-c7f3-4e83-81b5-3b066855aa6b)'
    appType: 'webApp'
    appName: 'DevOpsWeb'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'